# -*- coding: utf-8 -*-
"""midTerm_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10f63OGmFkKihEYwu3i3ry46SfnJLpmIM
"""

#2
import pandas as pd
import numpy as np

data = pd.read_csv("kbo_baseball_test.csv")

data["Winning Percentage"] = data["Win"] / data["Game"]
data["Rating"] = data["Winning Percentage"].rank(ascending=False, method='first').astype(int)
data = data.sort_values(by="Winning Percentage", ascending=False)

print("Top 5 of Winning Percentage")
for i in range(5):
    print("{}, {}".format(data["Team"].iloc[i], data["Rating"].iloc[i]))