# -*- coding: utf-8 -*-
"""midTerm_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RWcQ1qfGs1vrUNPsEuJY5K73wnyO6qah
"""

#5
import pandas as pd

df = pd.read_csv("seoul_ems_test.csv")
grouped = df.groupby('Region ID')[['2012', '2013', '2014', '2015', '2016', '2017']].sum()
matching = (grouped.sum(axis=1).reset_index(drop=True) == df['Total'])

# 1부터 25까지의 지역 ID에 대해 반복
for region_id in range(1, 26):
    is_matching = matching.get(region_id)
    if is_matching is not None:
        if not is_matching:
            total_value = df.at[region_id, 'Total']
            sum_2012_2017 = grouped.loc[region_id].sum()
            gap = total_value - sum_2012_2017
            print(f"지역 ID: {region_id}, 일치 여부: False, 차이: {gap}")
        else:
            print(f"지역 ID: {region_id}, 일치 여부: True")