# -*- coding: utf-8 -*-
"""midTerm_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gE5c0Zng0A54JbJ_bsSeASMEuniZTNnJ
"""

#1
import pandas as pd

data = pd.read_csv("attraction_list_1.csv", encoding="utf-8").fillna(0)
data = data[~data['자치구별'].str.contains('합계')]
selected_columns = ['자치구별', '관광지별'] + [str(year) for year in range(2013, 2023)]
data = data[selected_columns]
pivot_table = data.pivot_table(index='자치구별', columns=['관광지별'], values=[str(year) for year in range(2013, 2023)])
pivot_table = pivot_table.fillna(0)

print(pivot_table)