# -*- coding: utf-8 -*-
"""midTerm_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QUcZKDo5lMfqiftcdnScilC9gMQ8guH
"""

#4

import numpy as np
import pandas as pd

data = [
    290, 169, 183, 3, 227, 117, 159, 163, 240, 38, 23, 266, 96, 56, 280, 143, 246, 147, 226, 141, 290, 181, 0, 293, 260, 125, 29, 69, 184, 29, 2, 268, 202, 205, 271, 240, 151, 103, 204, 79, 154, 4, 229, 132, 138, 75, 31, 105, 62, 94, 285, 21, 289, 255, 69, 124, 178, 57, 106, 286, 52, 211, 58, 3, 147, 12, 273, 58, 246, 19
]


data_np = np.array(data)

data_series = pd.Series(data)

mean_np = np.mean(data_np)
mean_pd = data_series.mean()


variance_np = np.var(data_np)
variance_pd = data_series.var()


std_deviation_np = np.std(data_np)
std_deviation_pd = data_series.std()


median_np = np.median(data_np)
median_pd = data_series.median()

# 하위 20%, 80% 값
percentile_20_np = np.percentile(data_np, 20)
percentile_80_np = np.percentile(data_np, 80)

percentile_20_pd = data_series.quantile(0.20)
percentile_80_pd = data_series.quantile(0.80)

print("평균 (Numpy):", mean_np)
print("평균 (Pandas):", mean_pd)
print("분산 (Numpy):", variance_np)
print("분산 (Pandas):", variance_pd)
print("표준편차 (Numpy):", std_deviation_np)
print("표준편차 (Pandas):", std_deviation_pd)
print("중간값 (Numpy):", median_np)
print("중간값 (Pandas):", median_pd)
print("하위 20% 값 (Numpy):", percentile_20_np)
print("상위 20% 값 (Numpy):", percentile_80_np)
print("하위 20% 값 (Pandas):", percentile_20_pd)
print("상위 20% 값 (Pandas):", percentile_80_pd)