# -*- coding: utf-8 -*-
"""midTerm_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECu9_cEYIn_7sMHiWT-MDcHlpaiCul-C
"""

#3
import pandas as pd
import numpy as np

df1_data = np.ones((6,7))
df1 = pd.DataFrame(df1_data, index=list('abcdef'), columns=list('ABCDEFG'))
df2_data = np.ones((7,6))
df2 = pd.DataFrame(df2_data, index=list('abcdefg'), columns=list('ABCDEF'))
df3 = df1+df2

df3.loc['a', ['A', 'B', 'C', 'D', 'E', 'F', 'G']] = [np.nan, 2.0, 2.0, np.nan, np.nan, 2.0, np.nan]
df3.loc['b', ['A', 'B', 'C', 'D', 'E', 'F', 'G']] = [3.0, 3.0, 3.0, np.nan, np.nan, 2.0, np.nan]
df3.loc['c', ['A', 'B', 'C', 'D', 'E', 'F', 'G']] = [3.0, 3.0, 3.0, np.nan, np.nan, 2.0, np.nan]
df3.loc['d':'e', :] = np.nan

print(df3)